---
abstract: 'Simple Interface To Web Services APIs'
author: 'Yusuke Wada  C<< <yusuke@kamawada.com> >>'
build_requires:
  Test::More: 0
  Test::Pod: 0
distribution_type: module
generated_by: 'Module::Install version 0.67'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: WebService-Simple
no_index:
  directory:
    - inc
    - t
recommends:
  XML::LibXML: 0
requires:
  Class::Accessor::Fast: 0
  Class::Data::ConfigHash: 0
  Class::Inspector: 0
  Data::Dumper: 0
  Digest::MD5: 0
  JSON: 2.0
  LWP::UserAgent: 0
  UNIVERSAL::require: 0
  XML::Simple: 0
version: 0.04
